// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_MZ5F3sFH4cGQwQeq-Cp2OAkKUzbrsc4',
    appId: '1:304159055664:web:6b4a8eb0ad73a0306132f5',
    messagingSenderId: '304159055664',
    projectId: 'hackatonproject-90e9b',
    authDomain: 'hackatonproject-90e9b.firebaseapp.com',
    storageBucket: 'hackatonproject-90e9b.appspot.com',
    measurementId: 'G-C7SN7LJSS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMF-_F8D_oA-MhuI2y17h6I0ydJgc5YGE',
    appId: '1:304159055664:android:30a2e4fb0d1b17526132f5',
    messagingSenderId: '304159055664',
    projectId: 'hackatonproject-90e9b',
    storageBucket: 'hackatonproject-90e9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZuZktM0HPupsBtW5WQIPiUdZ_SmvdNTA',
    appId: '1:304159055664:ios:969464538234e3326132f5',
    messagingSenderId: '304159055664',
    projectId: 'hackatonproject-90e9b',
    storageBucket: 'hackatonproject-90e9b.appspot.com',
    iosClientId: '304159055664-svb7kvt9admb81sngvtieq8hc18rdfl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.sqaureProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZuZktM0HPupsBtW5WQIPiUdZ_SmvdNTA',
    appId: '1:304159055664:ios:969464538234e3326132f5',
    messagingSenderId: '304159055664',
    projectId: 'hackatonproject-90e9b',
    storageBucket: 'hackatonproject-90e9b.appspot.com',
    iosClientId: '304159055664-svb7kvt9admb81sngvtieq8hc18rdfl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.sqaureProject',
  );
}
